apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mongo-deploy
  name: mongo-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo-deploy
status:
  loadBalancer: {}