apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo-deploy
  name: mongo-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo-deploy
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
            - containerPort: 27017
              protocol: TCP
        volumeMounts:
            - mountPath: /data/db
              name: mongo-db-vol
        resources: {}
      volumes:
        - name: mongo-db-vol
          hostPath:
            path: /var/lib/docker/volumes/mongo-db-vol/_data
            type: DirectoryOrCreate
status: {}