apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mongo-deploy
  name: mongo-service
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 30001
  selector:
    app: mongo-deploy
  type: NodePort
status:
  loadBalancer: {}
# apiVersion: v1
# kind: Service
# metadata:
#   creationTimestamp: null
#   labels:
#     app: mongo-service
#   name: mongo-service
# spec:
#   ports:
#   - name: 27017-30001
#     port: 27017
#     protocol: TCP
#     targetPort: 30001
#   selector:
#     app: mongo-service
#   type: ClusterIP
# status:
#   loadBalancer: {}