apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: back-end-deploy
  name: back-end-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30002
  selector:
    app: back-end-deploy
  type: NodePort
status:
  loadBalancer: {}