apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: back-end-deploy
  name: back-end-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-end-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: back-end-deploy
    spec:
      containers:
      - image: back-end:1.0
        name: back-end
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
          - name: RUN_ENV
            value: development
          - name: MONGO_DOMAIN
            value: mongo-service.default.svc.cluster.local
          - name: MONGO_PORT
            value: '27017'
        resources: {}
status: {}