apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ui-deploy
  name: ui-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ui-deploy
    spec:
      containers:
      - image: front-end:1.3
        name: front-end
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
          - name: REACT_APP_BACKEND_DOMAIN
            value: 172.16.226.252
          - name: REACT_APP_BACKEND_PORT
            value: '30002'
        resources: {}
status: {}