apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ui-deploy
  name: ui-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ui-deploy
    spec:
      containers:
      - image: front-end:1.0
        name: front-end
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources: {}
status: {}