apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ui-deploy
  name: ui-service
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003
  selector:
    app: ui-deploy
  type: NodePort